# Exported from Render on 2026-03-19T12:16:00Z
version: "1"
services:
- type: web
  name: p2p-fileshare
  runtime: node
  repo: https://github.com/div02-afk/SimpleShare
  plan: free
  envVars:
  - key: CLOUDFLARE_TOKEN_ID
    sync: false
  - key: CLOUDFLARE_API_KEY
    sync: false
  region: singapore
  buildCommand: pnpm install --frozen-lockfile && pnpm build:server
  startCommand: pnpm --filter p2p-fileshare-server start
  healthCheckPath: /healthz
  autoDeployTrigger: commit
  buildFilter:
    paths:
    - apps/signalling-server
  previews:
    generation: automatic

